version: '3'


services:
  hello_py:
    build: .
    ports:
      - 80:5000
    networks: 
      - default
    container_name: 
      hello_py 
    restart:
      always
networks:
  default:
    driver: bridge

